import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def plot_2d_data(nx, ny, L):
    """
    Reads data from CSV files generated by the C++ code and plots them.

    Args:
        nx (int): Number of grid points in the x-direction.
        ny (int): Number of grid points in the y-direction.
        L (float): Spatial domain size.
    """
    
    # --- 1. Load Data ---
    try:
        psi_df = pd.read_csv("psi_2d_data.csv")
        V_df = pd.read_csv("potential_2d_data.csv")
    except FileNotFoundError as e:
        print("Error: {e}")
        print("Please ensure you have compiled and run the C++ program first to generate the CSV files.")
        return
    except Exception as e:
        print("An unexpected error occurred while reading the files: {e}")
        return

    # --- 2. Reshape Data for Plotting ---
    
    # Extract coordinates
    x_coords = psi_df['x_coord'].unique()
    y_coords = psi_df['y_coord'].unique()

    # Reshape probability density (|psi|^2)
    psi_squared = psi_df['probability_density'].values.reshape(ny, nx)
    
    # Reshape potential energy V(x,y)
    potential_energy = V_df['potential_energy'].values.reshape(ny, nx)

    # --- 3. Create Plots ---
    
    fig, axes = plt.subplots(1, 2, figsize=(16, 7))
    
    # --- Plot 1: Probability Density (|psi|^2) ---
    ax1 = axes[0]
    
    # Use pcolormesh for a good representation of grid data
    contour1 = ax1.pcolormesh(x_coords, y_coords, psi_squared, shading='auto', cmap='viridis')
    fig.colorbar(contour1, ax=ax1, label='$|\\psi|^2$')
    
    ax1.set_title('Converged Probability Density $|\\psi|^2$')
    ax1.set_xlabel('x (a.u.)')
    ax1.set_ylabel('y (a.u.)')
    ax1.set_aspect('equal', adjustable='box')
    
    # --- Plot 2: Potential Energy V(x,y) ---
    ax2 = axes[1]
    
    contour2 = ax2.pcolormesh(x_coords, y_coords, potential_energy, shading='auto', cmap='coolwarm')
    fig.colorbar(contour2, ax=ax2, label='$V(x,y)$')
    
    # Add contour lines of the potential for better visualization
    ax2.contour(x_coords, y_coords, potential_energy, levels=10, colors='k', alpha=0.3, linewidths=0.5)

    ax2.set_title('Potential Energy Surface $V(x,y)$')
    ax2.set_xlabel('x (a.u.)')
    ax2.set_ylabel('y (a.u.)')
    ax2.set_aspect('equal', adjustable='box')

    plt.tight_layout()
    plt.show()

# --- Execution ---
if __name__ == "__main__":
    # These parameters must match the constants in the C++ file
    NX = 1585
    NY = 1585
    L = 2.8
    
    print("Attempting to load data and plot...")
    plot_2d_data(NX, NY, L)
